.\"Copyright 2012 (c) EPFL
.TH EEGDEV-BIOSEMI 5 2012 "EPFL" "EEGDEV library manual"
.SH NAME
eegdev-biosemi - eegdev backend for Biosemi ActiveTwo hardware
.SH DESCRIPTION
.LP
The \fBbiosemi\fP plugin implements the backend for the eegdev library for
Biosemi Activetwo hardware. It supports both Mk1 and Mk2 models.
.SH CONFIGURATION
.LP
This plugin supports several options. The default value will be used
if none of the configuration files nor the configuration string (see
\fBegd_open\fP(3)) specify the option.
.TP
.B numch
Number of channel that should be supported by the BIOSEMI system. Accepted
values are \fB32\fP, \fB64\fP, \fB128\fP or \fB256\fP. Beware that the value
can be set superior to the actual number of ADC subsystem embedded into the
acquisition hardware. If it is the case, the additional channel will return
always 0. The default value is "64".
.SH FILES
.IP "/etc/eegdev/eegdev.conf" 4
.PD
Shared configuration file.
.IP "/etc/eegdev/biosemi.conf" 4
.PD
Configuration file loaded when the plugin is used. The settings specified
here overrides the settings in the shared configuration file.
.SH "SEE ALSO"
.BR egd_open (3),
.BR eegdev-options (5)

