.\"Copyright 2011 (c) EPFL
.TH EEGDEV-OPEN-OPTIONS 5 2011 "EPFL" "EEGDEV library manual"
.SH NAME
eegdev-open-options - Device configuration format specification
.SH DESCRIPTION
.SS "Syntax of the configuration string"
.LP
The device configuration string should follow the syntax:
.LP
.ce
device[[|option1|value1]...[|optionN|valueN]]
.LP
If the specified device does not support a certain pair of option|value,
this will be silently ignored by the opening function. \fIdevice\fP should
be the name of a eegdev plugin or \fBany\fP. In the later case, it will try
to open one of the devices supported by the installed plugins.
.SS "Syntax of the configuration files"
.LP
The configuration files are made of statements (at most one per line)
following this syntax (whitespace are ignored):
.ce
option = value
.LP
Comments are preceded by the '#' character:
.sp
.in +4n
.nf
# comment line 1
# comment line 2
option = value #comment2
.fi
.in
.SH FILES
.IP "/etc/eegdev/eegdev.conf" 4
.PD
Shared configuration file.
.IP "/etc/eegdev/<plugin>.conf" 4
.PD
Configuration file loaded when the plugin \fI<plugin>\fP is used. The
settings specified here overrides the settings in the shared configuration
file.
.SH EXAMPLES
.SS "Configuration string examples"
.LP
Device sourcing its data from the GDF file located at "/home/user/data.gdf":
.ce
datafile|path|/home/user/data.gdf
.LP
Biosemi device configured to use 32 electrodes:
.ce
biosemi|numch|32
.LP
gTec system consisting in a chain of 2 systems (the first 2 available)
with a notch filter at 60Hz without lowpass or highpass sampling at 512Hz 
(default sampling rate):
.ce
gtec|notch|60|lowpass|none|highpass|none|deviceid|any+any
.LP
Any supported type of device but should have the serial number UB-2009.10.06
if it is a gTec system:
.ce
any|deviceid|UB-2009.10.06
.SS "Configuration file example"
.sp
.in +4n
.nf
# gTec configuration examples
notch  = 60 # Notch value for USA
lowpass =none
highpass=none

 # Specify a coupled system by default
deviceid = any+any
.fi
.in
.SH "SEE ALSO"
.BR egd_open (3)
