.\"Copyright 2010 (c) EPFL
.TH EGD_CLOSE 3 2010 "EPFL" "EEGDEV library manual"
.SH NAME
egd_close - close a device
.SH SYNOPSIS
.LP
.B #include <eegdev.h>
.sp
.BI "int egd_close(struct eegdev* " dev ");"
.br
.SH DESCRIPTION
.LP
\fBegd_close\fP() frees all resources associated to the device referenced by
\fIdev\fP and closes it. It stops also implicitly any running acquisition. If
\fIdev\fP is NULL, no operation is done and the function will silently return.
.LP
After a successful call to \fBegd_close\fP(), the reference \fIdev\fP cannot
be used any longer.
.SH "RETURN VALUE"
.LP
The function always returns 0. It currently cannot fails but a value is
returned to accomodate possible future change.
